recipe: default.v1

language: en

pipeline:
  - name: SpacyNLP
    model: "en_ner_bc5cdr_md"
    case_sensitive: false
  - name: SpacyTokenizer
  - name: SpacyFeaturizer
    pooling: "mean"
  - name: SpacyEntityExtractor
    dimensions: [ 'DISEASE' ]
  - name: RegexFeaturizer
  - name: LanguageModelFeaturizer
    model_name: "bert"
    model_weights: "rasa/LaBSE"
    alias : LanguageModelFeaturizer
  - name: DIETClassifier
    random_seed: 43
    epochs: 120
    learning_rate: 0.001
    use_masked_language_model: True
    constrain_similarities: True
    tensorboard_log_directory: "./tensorboard"
    tensorboard_log_level: "epoch"
    featurizers : [LanguageModelFeaturizer]
#    entity_recognition : False
  - name: FallbackClassifier
    threshold: 0.6
    ambiguity_threshold: 0.2


policies:
  - name: MemoizationPolicy
  - name: RulePolicy
  - name: TEDPolicy
    max_history: 5
    epochs: 100
    constrain_similarities: true
    tensorboard_log_directory: "./tensorboard"
    tensorboard_log_level: "epoch"
