#https://rasa.com/docs/rasa/tuning-your-model/
# This ois a recommended Rasa pipeline


# The config recipe.
# https://rasa.com/docs/rasa/model-configuration/
recipe: default.v1

# Configuration for Rasa NLU.
# https://rasa.com/docs/rasa/nlu/components/
language: en

pipeline:
  - name: SpacyNLP
    model: "en_ner_bc5cdr_md"
    case_sensitive: false
  - name: SpacyTokenizer
  - name: SpacyFeaturizer
    pooling: "mean"
  - name: SpacyEntityExtractor
    dimensions: [ 'DISEASE' ]
  - name: RegexFeaturizer
  - name: LanguageModelFeaturizer
    model_name: "bert"
    model_weights: "rasa/LaBSE"
    alias : LanguageModelFeaturizer
  - name: DIETClassifier
    random_seed: 43
    epochs: 200
    learning_rate: 0.001 #10 power -6
    use_masked_language_model: True
#    entity_recognition : False
    constrain_similarities: True
    featurizers : [LanguageModelFeaturizer]
  - name: FallbackClassifier
    threshold: 0.6
    ambiguity_threshold: 0.2


policies:
  - name: MemoizationPolicy
  - name: RulePolicy
  - name: TEDPolicy
    max_history: 5
    epochs: 100
    constrain_similarities: true
  - name: UnexpecTEDIntentPolicy
    max_history: 5
    epochs: 100