version: "3.1"
nlu:
- intent: inform_symptoms
  examples: |
    - [headache](DISEASE)
    - [Dizziness](DISEASE) or [lightheadedness](DISEASE)
    - I have [blisters](DISEASE) on my hand
    - I have extreme [Fatigue] (DISEASE)
    - The rash usually appears on your trunk, arms or legs
    - My joints especially knees and wrists are stiff, [painful](DISEASE) and [inflamed](DISEASE).
    - I am getting [panic attacks](DISEASE)
    - I am observing [Chest pain] (DISEASE)
- intent: unhealthy_patient
  examples: |
    - I am not well
    - I am sick
    - I am feeling sooo bad today
    - I am freaking out
    - i am very sad
    - it is such a bad day for me
    - I am not so good
    - I'm dead
    - i am dead
    - very ill
- intent: bot_challenge
  examples: |
    - are you a real bot?
    - are you robot
    - who are you?
    - are you sure that you're a bot?
    - are you a chatbot
    - am i speaking to an ai?
    - are you artificial intelligence
    - what you do?
    - bot?
    - are you really a bot
    - are you a bot?
    - are you a rasa bot?
    - aren't you a bot
    - how can you help?
    - are you real
    - are you ai
    - are you a robot
    - are you a human or a bot?
- intent: greet
  examples: |
    - hallo
    - good evening
    - HEY
    - Hello
    - hi!
    - good morning
    - howdy
    - hello
    - hello there
    - hi there
    - HI
    - Hello?
    - Hola.
    - welcome
    - yo
    - good day
    - hello are you still there
    - Hi
- intent: healthy_patient
  examples: |
    - very happy
    - it is a good day for me
    - Fit as a fiddle
    - I am pretty well!
    - I am perfect!
    - I feel marvellous
    - Not bad
    - I am awesome
    - great
    - I am much better now, thank you
    - The best i can be
    - pretty well
    - I am feeling fantastic
    - I am great
    - I am very active today
    - I am alright
    - i am so great today
    - I am feeling good
    - very happy!
    - I'm ok
- intent: out_of_scope
  examples: |
    - what the weather today ?
    - order a pizza
    - hows the weather
    - what is the weather
    - ewfn rwtot43uf 345653tf 314efyj f ewu
    - lhfjdkwhnf
    - my washing machine isn't working
    - Can you call me back ?
    - a b c d d e f
    - Can you give me your datacenter's password?
    - what is the meaning of life.
    - my tv isn't working
    - Can you make sandwiches?
    - I want to order a pizza
    - Can YouTube talk?
    - what is the square root of 5
    - what year is it
    - tell me a joke
    - I want to order food
    - Can you give me your datacenter's password
    - ofif fsdfafsfs
    - Can you please send me an uber
    - bla bla bla
    - what is the weather today
    - Who's the US President?
- intent: goodbye
  examples: |
    - bye udo
    - good bye
    - gotta go
    - um okay thank you good bye
    - good job bot
    - thanks goodbye
    - thank you goodbye
    - okay thank you
    - Adios
    - byee
    - goodbye
    - goodnight
    - thx
    - ok i gtg
    - bye bye
    - catch you later
    - good night
    - i'm done
    - ciao
    - bye!
    - and thats all thank you and good bye
    - farewell
    - okay thank you goodbye
    - thnaks
    - see you later!
    - have a good day. time to go, bye
    - cya
    - great! thanks!
    - thank you bye
    - quit
    - thanks!
    - thanks
    - gracias
    - Thanks a lot. See ya later
    - thnks
    - bye bye bot
    - good bye rasa bot!
    - thankyou
    - great!
    - bye was nice talking to you
    - thanks you
    - thank you
    - thanks for the help
    - stop
    - bye
